/**
 * Pure engine DATA — transcribed verbatim from the research-doc JSON EXPORT block
 * (Product Docs/Color Combination Research.md, "## JSON EXPORT"). NO logic lives here;
 * `colors.ts`/`skin.ts`/`combos.ts` derive everything else from these tables.
 *
 * GENERATED by scripts/_gen_data_tmp.js (since deleted) so the data stays a faithful
 * copy of the source of truth — a verification agent diffs this against the doc.
 *
 * The only edit applied to the raw doc is normalising the Brown base string
 * "Brown (recommended addition)" -> "Brown" (17 distinct bases, no "Maroon" base).
 */

// SkinTier is the canonical type from './types'; data.ts only consumes it (no re-export,
// so `export *` in index.ts has a single, unambiguous SkinTier source).
import type { SkinTier } from './types';

/**
 * One named shade in the vocabulary: a display name, its hex, and the base colour
 * it belongs to. 86 entries / 17 bases (most bases have 5 shades; Beige has 6).
 */
export interface ShadeVocabEntry {
  shade: string;
  hex: string;
  base: string;
}

/** A Monk Skin Tone swatch (lowercase hex, as published). */
export interface MstSwatch {
  mst: string;
  hex: string;
  tier: SkinTier;
}

/** Maps each of the app's 6 legacy depth labels onto MST shades + a tier (migration). */
export interface MstLabel {
  label: string;
  mst: string[];
  tier: string;
}

/**
 * The raw doc shape for a curated combination (snake_case, `gender:"Men"|"Women"`,
 * `category:"Formal"|"Casual"`). `top`/`bottom`/`accent` are usually shade names but
 * some are BASE names (e.g. `bottom:"Black"`) and accents may be finish words not in
 * the shade vocabulary (e.g. "Gold", "Silver", "Tan", "Pearl"). `combos.ts` normalises
 * this into the engine's `NormCombo`/`CuratedMeta` shapes.
 */
export interface RawCombo {
  top: string;
  bottom: string;
  accent: string | null;
  mood: string;
  category: string;
  gender: string;
  style_tag: string;
  descriptor: string | null;
  region: string;
  flatters: string[];
  why: string;
  occasion: string;
  timeless_or_trend: string;
}

/** A pairing the recommender must never auto-suggest (kept for About/sources copy). */
export interface AvoidEntry {
  pair: string;
  reason: string;
}

/**
 * Named shade vocabulary — all 86 entries in doc order. Brown's base string is
 * normalised from "Brown (recommended addition)" to "Brown".
 */
export const SHADE_VOCAB: ShadeVocabEntry[] = [
  { shade: "Optic White", hex: "#FFFFFF", base: "White" },
  { shade: "Cloud Dancer", hex: "#F0EEE9", base: "White" },
  { shade: "Chalk White", hex: "#F7F6F1", base: "White" },
  { shade: "Off-White", hex: "#FAF9F6", base: "White" },
  { shade: "Ivory", hex: "#FFFFF0", base: "White" },
  { shade: "Cream", hex: "#FFFDD0", base: "Cream" },
  { shade: "Eggshell", hex: "#F0EAD6", base: "Cream" },
  { shade: "Parchment", hex: "#F1E9D2", base: "Cream" },
  { shade: "Vanilla", hex: "#F3E5AB", base: "Cream" },
  { shade: "Cosmic Latte", hex: "#FFF8E7", base: "Cream" },
  { shade: "Ecru", hex: "#C2B280", base: "Beige" },
  { shade: "Sand", hex: "#CBBD93", base: "Beige" },
  { shade: "Tan", hex: "#D2B48C", base: "Beige" },
  { shade: "Camel", hex: "#C19A6B", base: "Beige" },
  { shade: "Taupe", hex: "#B38B6D", base: "Beige" },
  { shade: "Stone", hex: "#D8CDBA", base: "Beige" },
  { shade: "Khaki", hex: "#C3B091", base: "Khaki" },
  { shade: "Dark Khaki", hex: "#BDB76B", base: "Khaki" },
  { shade: "Chino", hex: "#BEB079", base: "Khaki" },
  { shade: "Light Fawn", hex: "#C8AD7F", base: "Khaki" },
  { shade: "Khaki Drab", hex: "#A89A68", base: "Khaki" },
  { shade: "Powder Blue", hex: "#B0E0E6", base: "Light Blue" },
  { shade: "Sky Blue", hex: "#87CEEB", base: "Light Blue" },
  { shade: "Baby Blue", hex: "#AFC9E2", base: "Light Blue" },
  { shade: "Chambray", hex: "#A8BFD0", base: "Light Blue" },
  { shade: "Ice Blue", hex: "#D6E5F0", base: "Light Blue" },
  { shade: "Cornflower", hex: "#6495ED", base: "Blue" },
  { shade: "Steel Blue", hex: "#4682B4", base: "Blue" },
  { shade: "French Blue", hex: "#3A6EA5", base: "Blue" },
  { shade: "Royal Blue", hex: "#4169E1", base: "Blue" },
  { shade: "Cobalt", hex: "#0047AB", base: "Blue" },
  { shade: "Navy", hex: "#000080", base: "Navy" },
  { shade: "Midnight Navy", hex: "#191970", base: "Navy" },
  { shade: "French Navy", hex: "#22335A", base: "Navy" },
  { shade: "Indigo", hex: "#2E3A59", base: "Navy" },
  { shade: "Slate Navy", hex: "#2C3E50", base: "Navy" },
  { shade: "Light Grey", hex: "#D3D3D3", base: "Grey" },
  { shade: "Silver", hex: "#C0C0C0", base: "Grey" },
  { shade: "Dove Grey", hex: "#8B8E95", base: "Grey" },
  { shade: "Slate Grey", hex: "#708090", base: "Grey" },
  { shade: "Heather Grey", hex: "#AEB0B3", base: "Grey" },
  { shade: "Charcoal", hex: "#36454F", base: "Charcoal" },
  { shade: "Graphite", hex: "#3B3B3B", base: "Charcoal" },
  { shade: "Gunmetal", hex: "#2A2D34", base: "Charcoal" },
  { shade: "Anthracite", hex: "#34373D", base: "Charcoal" },
  { shade: "Slate Charcoal", hex: "#2F4F4F", base: "Charcoal" },
  { shade: "True Black", hex: "#000000", base: "Black" },
  { shade: "Jet Black", hex: "#0A0A0A", base: "Black" },
  { shade: "Ink Black", hex: "#1B1B1F", base: "Black" },
  { shade: "Onyx", hex: "#353839", base: "Black" },
  { shade: "Off-Black", hex: "#222222", base: "Black" },
  { shade: "Olive", hex: "#708238", base: "Olive" },
  { shade: "Olive Drab", hex: "#6B6B3A", base: "Olive" },
  { shade: "Army Green", hex: "#5D6532", base: "Olive" },
  { shade: "Dark Olive", hex: "#556B2F", base: "Olive" },
  { shade: "Moss", hex: "#8A9A5B", base: "Olive" },
  { shade: "Forest Green", hex: "#228B22", base: "Forest Green" },
  { shade: "Hunter Green", hex: "#355E3B", base: "Forest Green" },
  { shade: "Pine Green", hex: "#2C5446", base: "Forest Green" },
  { shade: "Bottle Green", hex: "#2F4E3B", base: "Forest Green" },
  { shade: "Emerald", hex: "#2E8B57", base: "Forest Green" },
  { shade: "Mustard", hex: "#FFDB58", base: "Mustard" },
  { shade: "Golden Mustard", hex: "#C9A227", base: "Mustard" },
  { shade: "Ochre", hex: "#CB9D06", base: "Mustard" },
  { shade: "Dijon", hex: "#C49102", base: "Mustard" },
  { shade: "Amber Honey", hex: "#E1AD01", base: "Mustard" },
  { shade: "Rust", hex: "#B7410E", base: "Rust" },
  { shade: "Terracotta", hex: "#D76B30", base: "Rust" },
  { shade: "Burnt Orange", hex: "#CC5500", base: "Rust" },
  { shade: "Sienna", hex: "#9E4A28", base: "Rust" },
  { shade: "Brick", hex: "#8B3A2F", base: "Rust" },
  { shade: "Burgundy", hex: "#800020", base: "Burgundy" },
  { shade: "Wine", hex: "#722F37", base: "Burgundy" },
  { shade: "Maroon", hex: "#800000", base: "Burgundy" },
  { shade: "Oxblood", hex: "#4A0404", base: "Burgundy" },
  { shade: "Bordeaux", hex: "#5E2129", base: "Burgundy" },
  { shade: "Royal Purple", hex: "#5B4B8A", base: "Purple" },
  { shade: "Plum", hex: "#8E4585", base: "Purple" },
  { shade: "Aubergine", hex: "#4C3641", base: "Purple" },
  { shade: "Amethyst", hex: "#9966CC", base: "Purple" },
  { shade: "Lavender", hex: "#B19CD9", base: "Purple" },
  { shade: "Tobacco", hex: "#6B4423", base: "Brown" },
  { shade: "Chestnut", hex: "#954535", base: "Brown" },
  { shade: "Cognac", hex: "#8B4513", base: "Brown" },
  { shade: "Chocolate", hex: "#3F2A1D", base: "Brown" },
  { shade: "Espresso", hex: "#3B2417", base: "Brown" },
];

/** The 10 official MST swatches (lightest -> deepest); hex kept lowercase as in doc. */
export const MST_SWATCHES: MstSwatch[] = [
  { mst: "MST1", hex: "#f6ede4", tier: "Light" },
  { mst: "MST2", hex: "#f3e7db", tier: "Light" },
  { mst: "MST3", hex: "#f7ead0", tier: "Light" },
  { mst: "MST4", hex: "#eadaba", tier: "Medium" },
  { mst: "MST5", hex: "#d7bd96", tier: "Medium" },
  { mst: "MST6", hex: "#a07e56", tier: "Medium" },
  { mst: "MST7", hex: "#825c43", tier: "Deep" },
  { mst: "MST8", hex: "#604134", tier: "Deep" },
  { mst: "MST9", hex: "#3a312a", tier: "Deep" },
  { mst: "MST10", hex: "#292420", tier: "Deep" },
];

/** MST membership of each of the 3 depth tiers. */
export const SKIN_TIERS: Record<SkinTier, string[]> = {
  Light: ["MST1", "MST2", "MST3"],
  Medium: ["MST4", "MST5", "MST6"],
  Deep: ["MST7", "MST8", "MST9", "MST10"],
};

/** Legacy 6-label -> MST/tier mapping (for migrating old saved profiles). */
export const MST_LABEL_MAP: MstLabel[] = [
  { label: "Fair", mst: ["MST1", "MST2"], tier: "Light" },
  { label: "Light", mst: ["MST3"], tier: "Light" },
  { label: "Medium", mst: ["MST4", "MST5"], tier: "Medium" },
  { label: "Tan", mst: ["MST6"], tier: "Medium" },
  { label: "Deep", mst: ["MST7", "MST8"], tier: "Deep" },
  { label: "Rich", mst: ["MST9", "MST10"], tier: "Deep" },
];

/** The 45 curated combinations, every field verbatim from the doc. */
export const COMBINATIONS: RawCombo[] = [
  {
    top: "Optic White", bottom: "Navy", accent: "Oxblood",
    mood: "Corporate Blue", category: "Formal", gender: "Men",
    style_tag: "Classic", descriptor: "business",
    region: "Universal", flatters: ["all"],
    why: "Navy+white is the most versatile, universally flattering formal base.",
    occasion: "Office/interview", timeless_or_trend: "timeless",
  },
  {
    top: "Optic White", bottom: "Charcoal", accent: "True Black",
    mood: "Boardroom Authority", category: "Formal", gender: "Men",
    style_tag: "Classic", descriptor: null,
    region: "Universal", flatters: ["all"],
    why: "Charcoal projects authority; white maximises crisp contrast.",
    occasion: "Business formal", timeless_or_trend: "timeless",
  },
  {
    top: "Sky Blue", bottom: "Navy", accent: "Cognac",
    mood: "Quiet Confidence", category: "Formal", gender: "Men",
    style_tag: "Classic", descriptor: null,
    region: "Universal", flatters: ["all"],
    why: "Light-on-dark blue tonal harmony; warmer than white, still sharp.",
    occasion: "Office", timeless_or_trend: "timeless",
  },
  {
    top: "Optic White", bottom: "Slate Navy", accent: "Burgundy",
    mood: "Power Meeting", category: "Formal", gender: "Men",
    style_tag: "Classic", descriptor: null,
    region: "Universal", flatters: ["all"],
    why: "Navy+burgundy is a timeless confident accent pairing.",
    occasion: "Meetings", timeless_or_trend: "timeless",
  },
  {
    top: "Light Grey", bottom: "Charcoal", accent: "Silver",
    mood: "Monochrome Steel", category: "Formal", gender: "Men",
    style_tag: "Minimal", descriptor: "tonal",
    region: "Universal", flatters: ["Medium", "Deep"],
    why: "Tonal grey is restrained and modern; deeper skin gives needed contrast.",
    occasion: "Office", timeless_or_trend: "timeless",
  },
  {
    top: "Optic White", bottom: "Black", accent: "True Black",
    mood: "Black Tie", category: "Formal", gender: "Men",
    style_tag: "Classic", descriptor: "formal",
    region: "Universal", flatters: ["all"],
    why: "The black evening standard; crisp white flatters near the face.",
    occasion: "Black tie", timeless_or_trend: "timeless",
  },
  {
    top: "Cream", bottom: "Tan", accent: "Tobacco",
    mood: "Summer Linen", category: "Formal", gender: "Men",
    style_tag: "Classic", descriptor: "warm",
    region: "Mediterranean/Italian", flatters: ["Medium", "Deep"],
    why: "Warm neutral-on-neutral; ideal warm-weather formal.",
    occasion: "Summer wedding", timeless_or_trend: "timeless",
  },
  {
    top: "Optic White", bottom: "Bottle Green", accent: "Cognac",
    mood: "Emerald Gentleman", category: "Formal", gender: "Men",
    style_tag: "Bold", descriptor: null,
    region: "UK/countryside", flatters: ["all"],
    why: "Green suit is a confident classic-adjacent statement; white keeps it formal.",
    occasion: "Cocktail", timeless_or_trend: "timeless",
  },
  {
    top: "Sky Blue", bottom: "Dove Grey", accent: "Navy",
    mood: "Interview Ready", category: "Formal", gender: "Men",
    style_tag: "Classic", descriptor: null,
    region: "Universal", flatters: ["all"],
    why: "Grey+blue balances intellect and approachability.",
    occasion: "Interview", timeless_or_trend: "timeless",
  },
  {
    top: "Optic White", bottom: "Wine", accent: "Charcoal",
    mood: "Cocktail Wine", category: "Formal", gender: "Men",
    style_tag: "Statement", descriptor: null,
    region: "Universal", flatters: ["all"],
    why: "Burgundy suit is a bold-but-wearable cocktail move grounded by neutral white.",
    occasion: "Cocktail", timeless_or_trend: "timeless",
  },
  {
    top: "Lavender", bottom: "Navy", accent: "Dove Grey",
    mood: "Soft Modern", category: "Formal", gender: "Men",
    style_tag: "Classic", descriptor: "soft",
    region: "Universal", flatters: ["all"],
    why: "Pale purple is a subtle modern shirt colour that flatters with navy.",
    occasion: "Office", timeless_or_trend: "timeless",
  },
  {
    top: "Optic White", bottom: "Navy", accent: "Tan",
    mood: "Corporate Blue", category: "Formal", gender: "Women",
    style_tag: "Classic", descriptor: "business",
    region: "Universal", flatters: ["all"],
    why: "Reliable boardroom palette; polished and authoritative.",
    occasion: "Office", timeless_or_trend: "timeless",
  },
  {
    top: "Ivory", bottom: "Charcoal", accent: "True Black",
    mood: "Executive Sharp", category: "Formal", gender: "Women",
    style_tag: "Classic", descriptor: null,
    region: "Universal", flatters: ["all"],
    why: "Charcoal suit + ivory is a strong, modern power look.",
    occasion: "Business formal", timeless_or_trend: "timeless",
  },
  {
    top: "Optic White", bottom: "Black", accent: "True Black",
    mood: "Monochrome Classic", category: "Formal", gender: "Women",
    style_tag: "Classic", descriptor: "monochrome",
    region: "Universal", flatters: ["all"],
    why: "Black+white is endlessly office-appropriate and crisp.",
    occasion: "Office", timeless_or_trend: "timeless",
  },
  {
    top: "Cream", bottom: "Camel", accent: "Gold",
    mood: "Quiet Luxury", category: "Formal", gender: "Women",
    style_tag: "Minimal", descriptor: "tonal",
    region: "Scandinavian", flatters: ["Medium", "Deep"],
    why: "Cream+camel tonal dressing whispers refinement.",
    occasion: "Office/lunch", timeless_or_trend: "timeless",
  },
  {
    top: "Emerald", bottom: "Black", accent: "True Black",
    mood: "Jewel Tone Power", category: "Formal", gender: "Women",
    style_tag: "Bold", descriptor: null,
    region: "Universal", flatters: ["all", "Deep"],
    why: "Jewel green pops against black; especially striking on deeper skin.",
    occasion: "Evening", timeless_or_trend: "timeless",
  },
  {
    top: "Lavender", bottom: "Light Grey", accent: "Silver",
    mood: "Serene Smart", category: "Formal", gender: "Women",
    style_tag: "Minimal", descriptor: "tonal",
    region: "Universal", flatters: ["all"],
    why: "Lavender + light grey is a smart, serene tone-on-tone pairing.",
    occasion: "Office", timeless_or_trend: "timeless",
  },
  {
    top: "Wine", bottom: "Navy", accent: "Tan",
    mood: "Autumn Boardroom", category: "Formal", gender: "Women",
    style_tag: "Classic", descriptor: null,
    region: "Universal", flatters: ["all"],
    why: "Wine + navy is balanced, rich and professional.",
    occasion: "Office", timeless_or_trend: "timeless",
  },
  {
    top: "Optic White", bottom: "Burgundy", accent: "Burgundy",
    mood: "Statement Wine", category: "Formal", gender: "Women",
    style_tag: "Statement", descriptor: null,
    region: "Universal", flatters: ["all"],
    why: "Burgundy suiting is expressive yet office-credible; white keeps it clean.",
    occasion: "Client-facing", timeless_or_trend: "timeless",
  },
  {
    top: "Sky Blue", bottom: "Navy", accent: "Silver",
    mood: "Soft Professional", category: "Formal", gender: "Women",
    style_tag: "Classic", descriptor: null,
    region: "Universal", flatters: ["all"],
    why: "Tonal blues read approachable and put-together.",
    occasion: "Office", timeless_or_trend: "timeless",
  },
  {
    top: "Plum", bottom: "Charcoal", accent: "Silver",
    mood: "Modern Plum", category: "Formal", gender: "Women",
    style_tag: "Bold", descriptor: null,
    region: "Universal", flatters: ["Medium", "Deep"],
    why: "Plum against charcoal is sophisticated and high-impact.",
    occasion: "Evening/office", timeless_or_trend: "timeless",
  },
  {
    top: "Optic White", bottom: "Indigo", accent: "Optic White",
    mood: "Clean Denim", category: "Casual", gender: "Men",
    style_tag: "Minimal", descriptor: null,
    region: "Universal", flatters: ["all"],
    why: "White tee + denim is the universal fail-safe casual look.",
    occasion: "Everyday", timeless_or_trend: "timeless",
  },
  {
    top: "Sky Blue", bottom: "Chino", accent: "Cognac",
    mood: "Smart Chino", category: "Casual", gender: "Men",
    style_tag: "Classic", descriptor: "smart-casual",
    region: "Universal", flatters: ["all"],
    why: "Light blue + khaki is a timeless smart-casual pairing.",
    occasion: "Office-casual", timeless_or_trend: "timeless",
  },
  {
    top: "Optic White", bottom: "Navy", accent: "Tobacco",
    mood: "Weekend Sharp", category: "Casual", gender: "Men",
    style_tag: "Classic", descriptor: "preppy",
    region: "Universal", flatters: ["all"],
    why: "White-on-navy chinos: crisp, versatile, never clashes.",
    occasion: "Weekend", timeless_or_trend: "timeless",
  },
  {
    top: "Olive", bottom: "Ecru", accent: "Optic White",
    mood: "Earthy Utility", category: "Casual", gender: "Men",
    style_tag: "Minimal", descriptor: "earthy",
    region: "Scandinavian/Japanese", flatters: ["Medium", "Deep"],
    why: "Olive + ecru is a natural warm-neutral earthy pairing.",
    occasion: "Weekend", timeless_or_trend: "timeless",
  },
  {
    top: "Navy", bottom: "Dove Grey", accent: "Optic White",
    mood: "Menswear Gold", category: "Casual", gender: "Men",
    style_tag: "Classic", descriptor: null,
    region: "Universal (Italian)", flatters: ["all"],
    why: "Navy + grey is the menswear gold standard, smart yet relaxed.",
    occasion: "Smart-casual", timeless_or_trend: "timeless",
  },
  {
    top: "Golden Mustard", bottom: "Navy", accent: "Tobacco",
    mood: "Autumn Pop", category: "Casual", gender: "Men",
    style_tag: "Bold", descriptor: null,
    region: "Universal", flatters: ["all", "Deep"],
    why: "Mustard against navy is a confident warm-cool contrast.",
    occasion: "Autumn weekend", timeless_or_trend: "timeless",
  },
  {
    top: "Off-Black", bottom: "True Black", accent: "True Black",
    mood: "Tokyo Mono", category: "Casual", gender: "Men",
    style_tag: "Minimal", descriptor: "monochrome",
    region: "Japanese/Tokyo", flatters: ["all", "Deep"],
    why: "All-black is the iconic Tokyo street-style uniform; deep skin carries it especially well.",
    occasion: "Evening/street", timeless_or_trend: "timeless",
  },
  {
    top: "Wine", bottom: "Stone", accent: "Cognac",
    mood: "Rich Casual", category: "Casual", gender: "Men",
    style_tag: "Bold", descriptor: null,
    region: "Universal", flatters: ["all"],
    why: "Wine + stone is warm, grounded and a touch dressy.",
    occasion: "Dinner", timeless_or_trend: "timeless",
  },
  {
    top: "Optic White", bottom: "Army Green", accent: "Optic White",
    mood: "Field Casual", category: "Casual", gender: "Men",
    style_tag: "Minimal", descriptor: "utility",
    region: "Japanese workwear", flatters: ["all"],
    why: "Olive + white is clean utilitarian; texture does the work.",
    occasion: "Everyday", timeless_or_trend: "timeless",
  },
  {
    top: "Hunter Green", bottom: "Ecru", accent: "Tobacco",
    mood: "Countryside", category: "Casual", gender: "Men",
    style_tag: "Classic", descriptor: "earthy",
    region: "UK", flatters: ["all"],
    why: "Green + ecru reads relaxed country-gentleman.",
    occasion: "Weekend", timeless_or_trend: "timeless",
  },
  {
    top: "Chambray", bottom: "Charcoal", accent: "Optic White",
    mood: "Easy Contrast", category: "Casual", gender: "Men",
    style_tag: "Minimal", descriptor: null,
    region: "Universal", flatters: ["all"],
    why: "Chambray + charcoal is an effortless mid-contrast casual look.",
    occasion: "Everyday", timeless_or_trend: "timeless",
  },
  {
    top: "Tobacco", bottom: "Ecru", accent: "Cream",
    mood: "Tonal Earth", category: "Casual", gender: "Men",
    style_tag: "Minimal", descriptor: "tonal/earthy",
    region: "Scandinavian", flatters: ["Medium", "Deep"],
    why: "Brown/cream/ecru tonal earth layering — warm and quietly luxurious.",
    occasion: "Autumn/winter", timeless_or_trend: "timeless",
  },
  {
    top: "Optic White", bottom: "Indigo", accent: "Tan",
    mood: "Effortless Denim", category: "Casual", gender: "Women",
    style_tag: "Minimal", descriptor: null,
    region: "Universal", flatters: ["all"],
    why: "White + denim: the universal everyday base.",
    occasion: "Everyday", timeless_or_trend: "timeless",
  },
  {
    top: "Cream", bottom: "Camel", accent: "Gold",
    mood: "Quiet Minimal", category: "Casual", gender: "Women",
    style_tag: "Minimal", descriptor: "tonal",
    region: "Scandinavian", flatters: ["Medium", "Deep"],
    why: "Cream + camel tonal neutrals epitomise quiet luxury.",
    occasion: "Everyday", timeless_or_trend: "timeless",
  },
  {
    top: "Sky Blue", bottom: "Stone", accent: "Optic White",
    mood: "Fresh Neutral", category: "Casual", gender: "Women",
    style_tag: "Minimal", descriptor: null,
    region: "Universal", flatters: ["all"],
    why: "Ice/sky blue refreshes warm neutrals for a modern, light look.",
    occasion: "Everyday", timeless_or_trend: "timeless",
  },
  {
    top: "Lavender", bottom: "Light Grey", accent: "Silver",
    mood: "Soft Serene", category: "Casual", gender: "Women",
    style_tag: "Minimal", descriptor: "tonal",
    region: "Universal", flatters: ["all"],
    why: "Lavender + grey is smart, calm and flattering.",
    occasion: "Everyday", timeless_or_trend: "timeless",
  },
  {
    top: "Olive", bottom: "Ecru", accent: "Tobacco",
    mood: "Earthy Edit", category: "Casual", gender: "Women",
    style_tag: "Minimal", descriptor: "earthy",
    region: "Scandinavian", flatters: ["Medium", "Deep"],
    why: "Olive + ecru is a directional, grounded earth pairing.",
    occasion: "Everyday", timeless_or_trend: "timeless",
  },
  {
    top: "Terracotta", bottom: "Olive", accent: "Tan",
    mood: "Soft Utility", category: "Casual", gender: "Women",
    style_tag: "Bold", descriptor: "earthy (outside palette: original blush pink, nearest = Terracotta/Rust)",
    region: "Trend-leaning", flatters: ["all"],
    why: "Terracotta/olive balances soft warmth with utilitarian green.",
    occasion: "Everyday", timeless_or_trend: "trend",
  },
  {
    top: "Wine", bottom: "Navy", accent: "Tobacco",
    mood: "Autumn Rich", category: "Casual", gender: "Women",
    style_tag: "Classic", descriptor: null,
    region: "Universal", flatters: ["all"],
    why: "Wine + navy: rich, balanced, seasonal.",
    occasion: "Autumn", timeless_or_trend: "timeless",
  },
  {
    top: "Optic White", bottom: "Black", accent: "True Black",
    mood: "Monochrome Chic", category: "Casual", gender: "Women",
    style_tag: "Classic", descriptor: "monochrome",
    region: "Universal/Tokyo", flatters: ["all"],
    why: "Black + white is timeless, sharp and universally wearable.",
    occasion: "Everyday/evening", timeless_or_trend: "timeless",
  },
  {
    top: "Golden Mustard", bottom: "Charcoal", accent: "Tobacco",
    mood: "Golden Hour", category: "Casual", gender: "Women",
    style_tag: "Bold", descriptor: null,
    region: "Universal", flatters: ["all", "Deep"],
    why: "Mustard glows against charcoal/denim; vivid yet wearable.",
    occasion: "Everyday", timeless_or_trend: "timeless",
  },
  {
    top: "Emerald", bottom: "Cream", accent: "Gold",
    mood: "Jewel Casual", category: "Casual", gender: "Women",
    style_tag: "Bold", descriptor: null,
    region: "Scandinavian", flatters: ["all", "Deep"],
    why: "Emerald against cream is fresh, organic and elevated.",
    occasion: "Everyday", timeless_or_trend: "timeless",
  },
  {
    top: "Off-Black", bottom: "True Black", accent: "Onyx",
    mood: "Tokyo Quiet", category: "Casual", gender: "Women",
    style_tag: "Minimal", descriptor: "monochrome",
    region: "Japanese/Tokyo", flatters: ["all", "Deep"],
    why: "Head-to-toe black is the quiet Tokyo uniform; saturation suits deep skin.",
    occasion: "Everyday/evening", timeless_or_trend: "timeless",
  },
  {
    top: "Ice Blue", bottom: "Navy", accent: "Optic White",
    mood: "Tonal Blue", category: "Casual", gender: "Women",
    style_tag: "Minimal", descriptor: "tonal",
    region: "Universal", flatters: ["all"],
    why: "Layered blues create sophisticated monochromatic depth.",
    occasion: "Everyday", timeless_or_trend: "timeless",
  },
];

/** The 10 "combinations to avoid" entries (reference / About copy). */
export const AVOID_LIST: AvoidEntry[] = [
  { pair: "Navy + Black", reason: "Too close to read as intentional; looks like a mismatch." },
  { pair: "Midnight Navy + Charcoal", reason: "Ambiguous near-match; reads as a failed full-suit." },
  { pair: "Brown + Burgundy", reason: "Muddy, low-contrast clash." },
  { pair: "Brown shoes + Black suit", reason: "Clashing; black shoes are the standard with a black suit." },
  { pair: "Red + Green (saturated)", reason: "Reads Christmas/costume." },
  { pair: "Purple + Yellow (saturated)", reason: "High-saturation clash, cartoonish." },
  { pair: "Rust + bright Red / Red + Orange", reason: "Sit too close, blur without contrast." },
  { pair: "Two non-matching blacks / off-white + grey-white", reason: "Looks accidental." },
  { pair: "Head-to-toe pale pastels on very light skin (near face)", reason: "Can wash out the complexion." },
  { pair: "Neon brights + earth tones", reason: "Neon flattens olive/rust/beige." },
];
